# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-02 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefile',
            name='downloads',
            field=models.IntegerField(default=0, verbose_name='Descargas'),
        ),
        migrations.AlterField(
            model_name='coursefile',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='coursefile',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Nombre'),
        ),
    ]
