# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 20:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0018_auto_20161027_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first', to='courses.Agenda')),
                ('second_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second', to='courses.Agenda')),
                ('third_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third', to='courses.Agenda')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
