# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-08 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('first_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_preference', to='courses.Agenda', verbose_name='Primera Preferencia')),
                ('second_preference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_preference', to='courses.Agenda', verbose_name='Segunda Preferencia')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
                ('third_preference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_preference', to='courses.Agenda', verbose_name='Tercera Preferencia')),
            ],
        ),
    ]
