# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-06 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, verbose_name='Nombre')),
                ('last_names', models.CharField(max_length=256, verbose_name='Apellidos')),
                ('usm_rol', models.CharField(max_length=12, verbose_name=b'Rol USM')),
                ('usm_priority', models.IntegerField(verbose_name=b'Prioridad USM')),
                ('psu_score', models.IntegerField(blank=True, help_text='Para alumnos de primer a\xf1o', null=True, verbose_name=b'Puntaje PSU')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('first_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first', to='courses.Agenda', verbose_name=b'Primera Preferencia')),
                ('second_preference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second', to='courses.Agenda', verbose_name=b'Segunda Preferencia')),
                ('third_preference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third', to='courses.Agenda', verbose_name=b'Tercera Preferencia')),
            ],
        ),
    ]
