# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-10 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('preregistration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistration',
            name='fifth_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fifth_preference', to='courses.Agenda', verbose_name='Quinta Preferencia'),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='fourth_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourth_preference', to='courses.Agenda', verbose_name='Cuarta Preferencia'),
        ),
    ]
