# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-02 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preregistration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregistration',
            name='first_preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first', to='courses.Agenda', verbose_name='Primera Preferencia'),
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='psu_score',
            field=models.IntegerField(blank=True, help_text='Para alumnos de primer año', null=True, verbose_name='Puntaje PSU'),
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='second_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second', to='courses.Agenda', verbose_name='Segunda Preferencia'),
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='third_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third', to='courses.Agenda', verbose_name='Tercera Preferencia'),
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='usm_priority',
            field=models.IntegerField(verbose_name='Prioridad USM'),
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='usm_rol',
            field=models.CharField(max_length=12, verbose_name='Rol USM'),
        ),
    ]
