# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-02 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20170602_0438'),
        ('preregistration', '0002_auto_20170602_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preregistration',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='preregistration',
            name='last_names',
        ),
        migrations.RemoveField(
            model_name='preregistration',
            name='usm_priority',
        ),
        migrations.RemoveField(
            model_name='preregistration',
            name='usm_rol',
        ),
        migrations.AddField(
            model_name='preregistration',
            name='student',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
            preserve_default=False,
        ),
    ]
