# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-10 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistration', '0002_auto_20170609_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregistration',
            name='fifth_preference',
            field=models.CharField(blank=True, choices=[(0, '1-2'), (1, '3-4'), (2, '5-6'), (3, '7-8'), (4, '9-10'), (5, '11-12'), (6, '13-14')], max_length=32, null=True, verbose_name='Quinta Preferencia'),
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='first_preference',
            field=models.CharField(choices=[(0, '1-2'), (1, '3-4'), (2, '5-6'), (3, '7-8'), (4, '9-10'), (5, '11-12'), (6, '13-14')], max_length=32, verbose_name='Primera Preferencia'),
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='fourth_preference',
            field=models.CharField(blank=True, choices=[(0, '1-2'), (1, '3-4'), (2, '5-6'), (3, '7-8'), (4, '9-10'), (5, '11-12'), (6, '13-14')], max_length=32, null=True, verbose_name='Cuarta Preferencia'),
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='second_preference',
            field=models.CharField(blank=True, choices=[(0, '1-2'), (1, '3-4'), (2, '5-6'), (3, '7-8'), (4, '9-10'), (5, '11-12'), (6, '13-14')], max_length=32, null=True, verbose_name='Segunda Preferencia'),
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='third_preference',
            field=models.CharField(blank=True, choices=[(0, '1-2'), (1, '3-4'), (2, '5-6'), (3, '7-8'), (4, '9-10'), (5, '11-12'), (6, '13-14')], max_length=32, null=True, verbose_name='Tercera Preferencia'),
        ),
    ]
