# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-30 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preregistration', '0002_auto_20170430_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregistration',
            name='psu_score',
            field=models.IntegerField(blank=True, help_text='Para alumnos de primer a\xf1o', null=True, verbose_name=b'Puntaje PSU'),
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='second_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second', to='courses.Agenda', verbose_name=b'Segunda Preferencia'),
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='third_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third', to='courses.Agenda', verbose_name=b'Tercera Preferencia'),
        ),
    ]
