# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-29 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
        ('preregistration', '0004_auto_20170615_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistration',
            name='software',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='misc.Software'),
            preserve_default=False,
        ),
    ]
