# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-08 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preregistration', '0004_remove_preregistration_psu_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregistration',
            name='first_preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_preference', to='courses.Agenda', verbose_name='Primera Preferencia'),
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='second_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_preference', to='courses.Agenda', verbose_name='Segunda Preferencia'),
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='third_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_preference', to='courses.Agenda', verbose_name='Tercera Preferencia'),
        ),
    ]
