# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-03 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistration', '0005_preregistration_software'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistration',
            name='parallel',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preregistration',
            name='previous_experience',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
