# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-02 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='public',
            field=models.BooleanField(default=False, help_text='Si es público, además, se mostrará a usuarios externos a la universidad.', verbose_name='Público'),
        ),
    ]
