# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-02 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='state',
            field=models.IntegerField(choices=[(0, 'Visible Sólo a Estudiantes'), (1, 'Visible a Público Externo')], default=0, verbose_name='Visibilidad'),
        ),
    ]
