version: "2"
services:
  postgres:
    image: postgres:latest
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=adn3
    ports:
      - "5432:5432"
    logging:
      driver: none

