# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-02 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlyIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='Nombre')),
                ('last_names', models.CharField(max_length=128, verbose_name='Apellidos')),
                ('rol', models.CharField(max_length=20, verbose_name='Rol USM')),
                ('usm_priority', models.IntegerField(verbose_name='Prioridad')),
                ('parallel', models.IntegerField()),
                ('previous_experience', models.BooleanField()),
                ('first_preference', models.CharField(choices=[('0-0', 'Lunes 1 - 2'), ('0-1', 'Lunes 3 - 4'), ('0-2', 'Lunes 5 - 6'), ('0-3', 'Lunes 7 - 8'), ('0-4', 'Lunes 9 - 10'), ('0-5', 'Lunes 11 - 12'), ('0-6', 'Lunes 13 - 14'), ('1-0', 'Martes 1 - 2'), ('1-1', 'Martes 3 - 4'), ('1-2', 'Martes 5 - 6'), ('1-3', 'Martes 7 - 8'), ('1-4', 'Martes 9 - 10'), ('1-5', 'Martes 11 - 12'), ('1-6', 'Martes 13 - 14'), ('2-0', 'Miércoles 1 - 2'), ('2-1', 'Miércoles 3 - 4'), ('2-2', 'Miércoles 5 - 6'), ('2-3', 'Miércoles 7 - 8'), ('2-4', 'Miércoles 9 - 10'), ('2-5', 'Miércoles 11 - 12'), ('2-6', 'Miércoles 13 - 14'), ('3-0', 'Jueves 1 - 2'), ('3-1', 'Jueves 3 - 4'), ('3-2', 'Jueves 5 - 6'), ('3-3', 'Jueves 7 - 8'), ('3-4', 'Jueves 9 - 10'), ('3-5', 'Jueves 11 - 12'), ('3-6', 'Jueves 13 - 14'), ('4-0', 'Viernes 1 - 2'), ('4-1', 'Viernes 3 - 4'), ('4-2', 'Viernes 5 - 6'), ('4-3', 'Viernes 7 - 8'), ('4-4', 'Viernes 9 - 10'), ('4-5', 'Viernes 11 - 12'), ('4-6', 'Viernes 13 - 14')], max_length=32, verbose_name='Primera Preferencia')),
                ('second_preference', models.CharField(blank=True, choices=[('0-0', 'Lunes 1 - 2'), ('0-1', 'Lunes 3 - 4'), ('0-2', 'Lunes 5 - 6'), ('0-3', 'Lunes 7 - 8'), ('0-4', 'Lunes 9 - 10'), ('0-5', 'Lunes 11 - 12'), ('0-6', 'Lunes 13 - 14'), ('1-0', 'Martes 1 - 2'), ('1-1', 'Martes 3 - 4'), ('1-2', 'Martes 5 - 6'), ('1-3', 'Martes 7 - 8'), ('1-4', 'Martes 9 - 10'), ('1-5', 'Martes 11 - 12'), ('1-6', 'Martes 13 - 14'), ('2-0', 'Miércoles 1 - 2'), ('2-1', 'Miércoles 3 - 4'), ('2-2', 'Miércoles 5 - 6'), ('2-3', 'Miércoles 7 - 8'), ('2-4', 'Miércoles 9 - 10'), ('2-5', 'Miércoles 11 - 12'), ('2-6', 'Miércoles 13 - 14'), ('3-0', 'Jueves 1 - 2'), ('3-1', 'Jueves 3 - 4'), ('3-2', 'Jueves 5 - 6'), ('3-3', 'Jueves 7 - 8'), ('3-4', 'Jueves 9 - 10'), ('3-5', 'Jueves 11 - 12'), ('3-6', 'Jueves 13 - 14'), ('4-0', 'Viernes 1 - 2'), ('4-1', 'Viernes 3 - 4'), ('4-2', 'Viernes 5 - 6'), ('4-3', 'Viernes 7 - 8'), ('4-4', 'Viernes 9 - 10'), ('4-5', 'Viernes 11 - 12'), ('4-6', 'Viernes 13 - 14')], max_length=32, null=True, verbose_name='Segunda Preferencia')),
                ('third_preference', models.CharField(blank=True, choices=[('0-0', 'Lunes 1 - 2'), ('0-1', 'Lunes 3 - 4'), ('0-2', 'Lunes 5 - 6'), ('0-3', 'Lunes 7 - 8'), ('0-4', 'Lunes 9 - 10'), ('0-5', 'Lunes 11 - 12'), ('0-6', 'Lunes 13 - 14'), ('1-0', 'Martes 1 - 2'), ('1-1', 'Martes 3 - 4'), ('1-2', 'Martes 5 - 6'), ('1-3', 'Martes 7 - 8'), ('1-4', 'Martes 9 - 10'), ('1-5', 'Martes 11 - 12'), ('1-6', 'Martes 13 - 14'), ('2-0', 'Miércoles 1 - 2'), ('2-1', 'Miércoles 3 - 4'), ('2-2', 'Miércoles 5 - 6'), ('2-3', 'Miércoles 7 - 8'), ('2-4', 'Miércoles 9 - 10'), ('2-5', 'Miércoles 11 - 12'), ('2-6', 'Miércoles 13 - 14'), ('3-0', 'Jueves 1 - 2'), ('3-1', 'Jueves 3 - 4'), ('3-2', 'Jueves 5 - 6'), ('3-3', 'Jueves 7 - 8'), ('3-4', 'Jueves 9 - 10'), ('3-5', 'Jueves 11 - 12'), ('3-6', 'Jueves 13 - 14'), ('4-0', 'Viernes 1 - 2'), ('4-1', 'Viernes 3 - 4'), ('4-2', 'Viernes 5 - 6'), ('4-3', 'Viernes 7 - 8'), ('4-4', 'Viernes 9 - 10'), ('4-5', 'Viernes 11 - 12'), ('4-6', 'Viernes 13 - 14')], max_length=32, null=True, verbose_name='Tercera Preferencia')),
                ('fourth_preference', models.CharField(blank=True, choices=[('0-0', 'Lunes 1 - 2'), ('0-1', 'Lunes 3 - 4'), ('0-2', 'Lunes 5 - 6'), ('0-3', 'Lunes 7 - 8'), ('0-4', 'Lunes 9 - 10'), ('0-5', 'Lunes 11 - 12'), ('0-6', 'Lunes 13 - 14'), ('1-0', 'Martes 1 - 2'), ('1-1', 'Martes 3 - 4'), ('1-2', 'Martes 5 - 6'), ('1-3', 'Martes 7 - 8'), ('1-4', 'Martes 9 - 10'), ('1-5', 'Martes 11 - 12'), ('1-6', 'Martes 13 - 14'), ('2-0', 'Miércoles 1 - 2'), ('2-1', 'Miércoles 3 - 4'), ('2-2', 'Miércoles 5 - 6'), ('2-3', 'Miércoles 7 - 8'), ('2-4', 'Miércoles 9 - 10'), ('2-5', 'Miércoles 11 - 12'), ('2-6', 'Miércoles 13 - 14'), ('3-0', 'Jueves 1 - 2'), ('3-1', 'Jueves 3 - 4'), ('3-2', 'Jueves 5 - 6'), ('3-3', 'Jueves 7 - 8'), ('3-4', 'Jueves 9 - 10'), ('3-5', 'Jueves 11 - 12'), ('3-6', 'Jueves 13 - 14'), ('4-0', 'Viernes 1 - 2'), ('4-1', 'Viernes 3 - 4'), ('4-2', 'Viernes 5 - 6'), ('4-3', 'Viernes 7 - 8'), ('4-4', 'Viernes 9 - 10'), ('4-5', 'Viernes 11 - 12'), ('4-6', 'Viernes 13 - 14')], max_length=32, null=True, verbose_name='Cuarta Preferencia')),
                ('fifth_preference', models.CharField(blank=True, choices=[('0-0', 'Lunes 1 - 2'), ('0-1', 'Lunes 3 - 4'), ('0-2', 'Lunes 5 - 6'), ('0-3', 'Lunes 7 - 8'), ('0-4', 'Lunes 9 - 10'), ('0-5', 'Lunes 11 - 12'), ('0-6', 'Lunes 13 - 14'), ('1-0', 'Martes 1 - 2'), ('1-1', 'Martes 3 - 4'), ('1-2', 'Martes 5 - 6'), ('1-3', 'Martes 7 - 8'), ('1-4', 'Martes 9 - 10'), ('1-5', 'Martes 11 - 12'), ('1-6', 'Martes 13 - 14'), ('2-0', 'Miércoles 1 - 2'), ('2-1', 'Miércoles 3 - 4'), ('2-2', 'Miércoles 5 - 6'), ('2-3', 'Miércoles 7 - 8'), ('2-4', 'Miércoles 9 - 10'), ('2-5', 'Miércoles 11 - 12'), ('2-6', 'Miércoles 13 - 14'), ('3-0', 'Jueves 1 - 2'), ('3-1', 'Jueves 3 - 4'), ('3-2', 'Jueves 5 - 6'), ('3-3', 'Jueves 7 - 8'), ('3-4', 'Jueves 9 - 10'), ('3-5', 'Jueves 11 - 12'), ('3-6', 'Jueves 13 - 14'), ('4-0', 'Viernes 1 - 2'), ('4-1', 'Viernes 3 - 4'), ('4-2', 'Viernes 5 - 6'), ('4-3', 'Viernes 7 - 8'), ('4-4', 'Viernes 9 - 10'), ('4-5', 'Viernes 11 - 12'), ('4-6', 'Viernes 13 - 14')], max_length=32, null=True, verbose_name='Quinta Preferencia')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.Software')),
            ],
        ),
    ]
