# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-07 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyin',
            name='usm_priority',
            field=models.FloatField(verbose_name='Prioridad'),
        ),
    ]
