# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-08 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyins', '0004_flyin_seen_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flyin',
            old_name='seen_details',
            new_name='seen',
        ),
    ]
