# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-04-17 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyins', '0006_flyin_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyin',
            name='usm_priority',
            field=models.FloatField(help_text='Se permite ingrsar puntaje PSU para estudiantes de primer año', verbose_name='Prioridad'),
        ),
    ]
