# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-08 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretestupload',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='pretestupload',
            name='pretest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pretests.Pretest', verbose_name='Preinforme'),
        ),
        migrations.AlterField(
            model_name='pretestupload',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.Software', verbose_name='Software'),
        ),
        migrations.AlterField(
            model_name='pretestupload',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student', verbose_name='Estudiante'),
        ),
    ]
