# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-02 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretests', '0002_auto_20170602_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretest',
            name='percentage',
            field=models.IntegerField(default=0, verbose_name='Porcentaje'),
        ),
    ]
