# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-06 01:43
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('misc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='\xcdndice')),
                ('text', models.TextField(verbose_name='Texto')),
                ('correct', models.BooleanField(default=False, verbose_name='Es correcta')),
            ],
            options={
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Enunciado')),
                ('score', models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Puntaje')),
                ('html', models.TextField(verbose_name='html')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nombre')),
                ('timeout', models.IntegerField(choices=[(15, '15 minutos'), (30, '30 minutos'), (45, '45 minutos'), (60, '1 hora'), (75, '1 hora 15 minutos'), (90, '1 hora 30 minutos'), (105, '1 hora 45 minutos')], verbose_name='Duraci\xf3n')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('show_grade', models.BooleanField(default=True, verbose_name='Mostrar nota')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('percentage', models.IntegerField(verbose_name='Porcentaje')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Curso')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Due\xf1o')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Session', verbose_name='Sesi\xf3n')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.Software', verbose_name='Software')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('index', models.IntegerField()),
                ('file', models.FileField(blank=True, upload_to=b'tests/')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Test', verbose_name=b'Control')),
            ],
            options={
                'verbose_name': 'Forma',
                'verbose_name_plural': 'Formas',
            },
        ),
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.Question')),
            ],
            bases=('tests.question',),
        ),
        migrations.CreateModel(
            name='NumericalQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.Question')),
                ('top_limit', models.FloatField(verbose_name='L\xedmite Superior')),
                ('bottom_limit', models.FloatField(verbose_name='L\xedmite Inferior')),
            ],
            bases=('tests.question',),
        ),
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.Question')),
            ],
            bases=('tests.question',),
        ),
        migrations.AddField(
            model_name='question',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Version', verbose_name='Forma'),
        ),
        migrations.AddField(
            model_name='alternative',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.ChoiceQuestion', verbose_name='Pregunta'),
        ),
    ]
