# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-09 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsanswers',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
