# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-06 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
