# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_version_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumericalQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.Question')),
                ('top_limit', models.FloatField()),
                ('bottom_limit', models.FloatField()),
            ],
            bases=('tests.question',),
        ),
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.Question')),
            ],
            bases=('tests.question',),
        ),
    ]
