# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-16 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_agendatest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='active',
        ),
        migrations.RemoveField(
            model_name='test',
            name='software',
        ),
    ]
