# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-03 03:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0002_auto_20170602_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Alternative', verbose_name='Alternativa')),
                ('choiceQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.ChoiceQuestion', verbose_name='Pregunta')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='NumericalAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.FloatField(verbose_name='Número')),
                ('numericalQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.NumericalQuestion', verbose_name='Pregunta')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='StudentsAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startedAt', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inicio')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Version', verbose_name='Forma')),
            ],
        ),
        migrations.CreateModel(
            name='TextAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texto')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
                ('textQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.TextQuestion', verbose_name='Pregunta')),
            ],
        ),
        migrations.AddField(
            model_name='choicequestion',
            name='answers',
            field=models.ManyToManyField(blank=True, through='tests.ChoiceAnswer', to=settings.AUTH_USER_MODEL, verbose_name='Respuestas'),
        ),
        migrations.AddField(
            model_name='numericalquestion',
            name='answers',
            field=models.ManyToManyField(blank=True, through='tests.NumericalAnswer', to=settings.AUTH_USER_MODEL, verbose_name='Respuestas'),
        ),
        migrations.AddField(
            model_name='textquestion',
            name='answers',
            field=models.ManyToManyField(blank=True, through='tests.TextAnswer', to=settings.AUTH_USER_MODEL, verbose_name='Respuestas'),
        ),
        migrations.AddField(
            model_name='version',
            name='student',
            field=models.ManyToManyField(blank=True, through='tests.StudentsAnswers', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante'),
        ),
    ]
