# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-22 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_studentsanswers_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='index',
        ),
    ]
