# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-03 03:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20170603_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numericalquestion',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='NumericalAnswers', through='tests.NumericalAnswer', to=settings.AUTH_USER_MODEL, verbose_name='Respuestas'),
        ),
    ]
