# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-24 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_remove_version_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ('create_date',), 'verbose_name': 'Forma', 'verbose_name_plural': 'Formas'},
        ),
    ]
