# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_numericalquestion_textquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='file',
            field=models.FileField(default='', upload_to=b'tests/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alternative',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.ChoiceQuestion', verbose_name='Pregunta'),
        ),
        migrations.AlterField(
            model_name='numericalquestion',
            name='bottom_limit',
            field=models.FloatField(verbose_name='L\xedmite Inferior'),
        ),
        migrations.AlterField(
            model_name='numericalquestion',
            name='top_limit',
            field=models.FloatField(verbose_name='L\xedmite Superior'),
        ),
    ]
