# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-29 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20170724_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsanswers',
            name='qualification',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
    ]
