# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-03 03:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20170603_0322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsanswers',
            old_name='startedAt',
            new_name='started_at',
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='choice_answers', through='tests.ChoiceAnswer', to=settings.AUTH_USER_MODEL, verbose_name='Respuestas'),
        ),
        migrations.AlterField(
            model_name='numericalquestion',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='numerical_answers', through='tests.NumericalAnswer', to=settings.AUTH_USER_MODEL, verbose_name='Respuestas'),
        ),
        migrations.AlterField(
            model_name='textquestion',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='text_answers', through='tests.TextAnswer', to=settings.AUTH_USER_MODEL, verbose_name='Respuestas'),
        ),
        migrations.AlterField(
            model_name='version',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='students', through='tests.StudentsAnswers', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante'),
        ),
    ]
