# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-03 03:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_auto_20170603_0342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='student',
            new_name='students',
        ),
    ]
