# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-05 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_auto_20170729_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='correct',
            field=models.NullBooleanField(verbose_name='Es correcta'),
        ),
    ]
