# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-30 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_auto_20161204_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='html',
            field=models.TextField(default='<p>tests</p>', verbose_name='html'),
            preserve_default=False,
        ),
    ]
