# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-08 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_auto_20170607_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceanswer',
            name='alternative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.Alternative', verbose_name='Alternativa'),
        ),
        migrations.AlterField(
            model_name='numericalanswer',
            name='number',
            field=models.FloatField(null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='textanswer',
            name='text',
            field=models.TextField(null=True, verbose_name='Texto'),
        ),
    ]
