# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-30 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_auto_20170430_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='html',
            field=models.TextField(verbose_name='html'),
        ),
    ]
