# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-08 04:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0008_auto_20170608_0400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
        ),
        migrations.RemoveField(
            model_name='choiceanswer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='choiceanswer',
            name='student',
        ),
        migrations.RemoveField(
            model_name='numericalanswer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='numericalanswer',
            name='student',
        ),
        migrations.RemoveField(
            model_name='textanswer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='textanswer',
            name='student',
        ),
        migrations.AddField(
            model_name='choiceanswer',
            name='answer_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.Answer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numericalanswer',
            name='answer_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.Answer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textanswer',
            name='answer_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.Answer'),
            preserve_default=False,
        ),
    ]
