# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-08 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_auto_20170608_0407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numericalanswer',
            old_name='numerical_question',
            new_name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='version',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='tests.Version', verbose_name='Forma'),
            preserve_default=False,
        ),
    ]
