# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-08 04:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_auto_20170608_0414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choiceanswer',
            old_name='choice_question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='textanswer',
            old_name='text_question',
            new_name='question',
        ),
    ]
