# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-08 04:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_auto_20170608_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='version',
        ),
        migrations.RemoveField(
            model_name='choiceanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='choicequestion',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='numericalanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='numericalquestion',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='textanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='textquestion',
            name='answers',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tests.Question', verbose_name='Pregunta'),
            preserve_default=False,
        ),
    ]
