# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-08 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_auto_20170608_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsanswers',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='choiceanswer',
            name='alternative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.Alternative', verbose_name='Alternativa'),
        ),
        migrations.AlterField(
            model_name='numericalanswer',
            name='number',
            field=models.FloatField(blank=True, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='textanswer',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Texto'),
        ),
    ]
