# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-08 16:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día')),
                ('block', models.IntegerField(choices=[(0, '1-2'), (1, '3-4'), (2, '5-6'), (3, '7-8'), (4, '9-10'), (5, '11-12'), (6, '13-14')], verbose_name='Bloque')),
                ('assistants', models.ManyToManyField(blank=True, related_name='assistants', to=settings.AUTH_USER_MODEL, verbose_name='Ayudantes')),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Campus',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Nombre')),
                ('code', models.CharField(max_length=16, verbose_name='Sigla')),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2)], verbose_name='Semestre')),
                ('year', models.IntegerField(choices=[(2016, 2016), (2017, 2017)], verbose_name='Año')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Campus')),
            ],
        ),
        migrations.CreateModel(
            name='CourseGradesConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_tests', models.FloatField(verbose_name='% Nota controles')),
                ('grade_pretests', models.FloatField(verbose_name='% Nota preinformes')),
                ('grade_assistance', models.FloatField(verbose_name='% Nota asistencia')),
                ('show_final_grade', models.BooleanField(default=True, verbose_name='Mostrar nota final')),
                ('course', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades_config', to='courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.BooleanField(verbose_name='Coordinador')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Curso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nombre')),
                ('code', models.CharField(max_length=32, verbose_name='Código')),
                ('seats', models.IntegerField(verbose_name='Asientos')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, through='courses.CourseTeacher', to=settings.AUTH_USER_MODEL, verbose_name='Profesores'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='inscriptions',
            field=models.ManyToManyField(blank=True, related_name='inscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Inscritos'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Room', verbose_name='Sala'),
        ),
    ]
