# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-02 00:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='block',
            field=models.IntegerField(choices=[(0, '1-2'), (1, '3-4'), (2, '5-6'), (3, '7-8'), (4, '9-10'), (5, '11-12'), (6, '13-14')], verbose_name='Bloque'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='day',
            field=models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, through='courses.CourseTeacher', to=settings.AUTH_USER_MODEL, verbose_name='Profesores'),
        ),
        migrations.AlterField(
            model_name='courseteacher',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='courseteacher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Profesor'),
        ),
    ]
