# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20161027_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(choices=[(2016, 2016), (2017, 2017)], verbose_name='A\xf1o'),
        ),
    ]
