# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-04 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20171001_1548'),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='registration.Student', verbose_name='Estudiante'),
            preserve_default=False,
        ),
    ]
