# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-24 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='usm_priority',
            field=models.IntegerField(null=True, verbose_name='Prioridad'),
        ),
    ]
