# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-01 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20170924_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='usm_priority',
            field=models.IntegerField(blank=True, null=True, verbose_name='Prioridad'),
        ),
    ]
