# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-25 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_agenda_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Código de inscripción'),
        ),
    ]
