# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-21 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20180310_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='campus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Campus'),
        ),
    ]
