# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-11 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_room_campus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ('day', 'block')},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-year', '-semester', 'code', 'campus')},
        ),
    ]
