# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-11 04:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_coursefiledownload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefiledownload',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
