# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-02 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.IntegerField(choices=[(0, 'Regular'), (1, 'Prueba'), (2, 'Recuperativa')], default=0, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='session',
            name='state',
            field=models.IntegerField(choices=[(0, 'Privada'), (1, 'Pública')], default=0, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='sessionfile',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='sessionfile',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Nombre'),
        ),
    ]
