# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-06 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pretestupload',
            name='qualification',
            field=models.IntegerField(null=True),
        ),
    ]
