# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-07 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretests', '0002_pretestupload_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='pretestupload',
            name='feedback',
            field=models.TextField(null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='pretestupload',
            name='qualification',
            field=models.IntegerField(null=True, verbose_name='Calificación'),
        ),
    ]
