# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-02 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretests', '0003_auto_20170906_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='pretest',
            name='online',
            field=models.BooleanField(default=False, verbose_name='Entrega Online'),
        ),
    ]
