# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-02 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretests', '0004_pretest_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretest',
            name='online',
            field=models.BooleanField(default=False, help_text='Permitirá al estudiante enviar un archivo a través del sistema, para que el encargado posteriormente lo descargue y evalúe.', verbose_name='Entrega Online'),
        ),
        migrations.AlterField(
            model_name='pretest',
            name='percentage',
            field=models.IntegerField(default=0, verbose_name='Porcentaje Nota'),
        ),
        migrations.AlterField(
            model_name='pretest',
            name='show_grade',
            field=models.BooleanField(default=False, help_text='Mostrará la calificación al estudiante posterior a la revisión.', verbose_name='Mostrar calificación'),
        ),
    ]
