# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-15 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20171005_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentsanswers',
            options={'ordering': ('pk',)},
        ),
    ]
