# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-19 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_auto_20171215_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ('create_date',)},
        ),
    ]
