# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-04-17 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20190417_1412'),
        ('tests', '0006_auto_20171219_1508'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agendatest',
            unique_together=set([('agenda', 'test')]),
        ),
    ]
